sudo: required
services:
  - docker
before_install:
  - docker build -t denissrezan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true denissrezan/react-test npm test

after_success:
  - docker build -t denissrezan/multi-client ./client
  - docker build -t denissrezan/multi-nginx ./nginx
  - docker build -t denissrezan/multi-server ./server
  - docker build -t denissrezan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push denissrezan/multi-client
  - docker push denissrezan/multi-nginx
  - docker push denissrezan/multi-server
  - docker push denissrezan/multi-worker
language: generic
